package:
  name: mayavi
  version: "4.5.0"

source:
  fn: mayavi-4.5.0.tar.bz2
  url: https://pypi.python.org/packages/19/f6/fde2f9bde7036c25b96d66d5ccf28c3ac14e5ecea92d0e5a6a0b2613f09f/mayavi-4.5.0.tar.bz2
  md5: 5bd57efc8fdff44ae603acdc60991c91

build:
  preserve_egg_dir: True
  entry_points:
    - mayavi2 = mayavi.scripts.mayavi2:main

requirements:
  build:
    - python
    - setuptools
    - envisage
    - pyqt
    - apptools
    - numpy
    - traits
    - traitsui
    - vtk 7.*

  run:
    - python
    - setuptools
    - envisage
    - pyqt
    - numpy
    - apptools
    - traits
    - traitsui
    - vtk 7.*

test:
  # Python imports
  imports:
    - mayavi
    - mayavi.action
    - mayavi.components
    - mayavi.components.ui
    - mayavi.core
    - mayavi.core.lut
    - mayavi.core.ui
    - mayavi.filters
    - mayavi.modules
    - mayavi.modules.ui
    - mayavi.plugins
    - mayavi.preferences
    - mayavi.scripts
    - mayavi.sources
    - mayavi.sources.ui
    - mayavi.tests
    - mayavi.tools
    - mayavi.tools.data_wizards
    - tvtk
    - tvtk.custom
    - tvtk.pipeline
    - tvtk.plugins
    - tvtk.plugins.browser
    - tvtk.plugins.scene
    - tvtk.plugins.scene.ui
    - tvtk.pyface
    - tvtk.pyface.ui
    - tvtk.pyface.ui.null
    - tvtk.pyface.ui.qt4
    - tvtk.pyface.ui.wx
    - tvtk.tests
    - tvtk.tools
    - tvtk.util
    - tvtk.view

  commands:
    - mayavi2 --help

about:
  home: http://code.enthought.com/projects/mayavi/
  license: BSD License
  summary: 'The Mayavi scientific data 3-dimensional visualizer.'
